spring:
  application:
    name: "project"

server:
  address: 0.0.0.0
  port: 8080

jwt:
  secret: "QG4M3VSnGqQff/+sfJKMvDTDIIIZdebMz9zudCRkxek="
  expiry-millis: 7200000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html